import { Template } from "./types";

// ─────────────────────────────────────────────────
//  GENERAL TEMPLATES
// ─────────────────────────────────────────────────

export const GENERAL_TEMPLATES: Template[] = [
  {
    id: "standard-group-project",
    name: "Standard Group Project",
    description:
      "End-to-end workflow for semester team assignments with clear milestones and review stages.",
    bestFor: "Course projects, capstone teams, lab groups",
    category: "General",
    columns: ["Planning", "Task Assignment", "In Progress", "Review", "Submission"],
    initialTasks: [
      { title: "Define project scope and deliverables", description: "Clarify the main objective, expected outputs, and boundaries of the project.", tags: ["Planning"], column: 0 },
      { title: "Set milestone deadlines", description: "Create a timeline with key milestones aligned to the course schedule.", tags: ["Planning"], column: 0 },
      { title: "Create shared workspace (Drive, Repo, etc.)", description: "Set up the shared collaboration environment for documents and code.", tags: ["Setup"], column: 0 },
      { title: "Assign roles to team members", description: "Distribute responsibilities based on strengths and interests.", tags: ["Team"], column: 1 },
      { title: "Break deliverables into individual tasks", description: "Decompose major deliverables into smaller, actionable items.", tags: ["Planning"], column: 1 },
      { title: "Set up communication channel", description: "Create a group chat or Slack/Discord channel for coordination.", tags: ["Setup"], column: 1 },
      { title: "Complete individual assigned tasks", description: "Each member works on their assigned portion.", tags: ["Work"], column: 2 },
      { title: "Draft initial report sections", description: "Begin writing your assigned sections of the project report.", tags: ["Writing"], column: 2 },
      { title: "Integrate all contributions", description: "Combine individual work into a unified document or deliverable.", tags: ["Work"], column: 2 },
      { title: "Peer review all sections", description: "Each member reviews at least one other section for quality.", tags: ["Review"], column: 3 },
      { title: "Format final document", description: "Apply consistent formatting, citations, and page layout.", tags: ["Writing"], column: 3 },
      { title: "Submit final deliverables", description: "Upload the final project to the course portal before the deadline.", tags: ["Submission"], column: 4 },
    ],
  },
  {
    id: "standard-kanban",
    name: "Classic Kanban",
    description:
      "Simple three-column board for any project that needs a lightweight workflow.",
    bestFor: "Quick personal projects, small teams",
    category: "General",
    columns: ["To Do", "In Progress", "Done"],
    initialTasks: [{ title: "First Task", tags: ["Getting Started"], column: 0 }],
  },
  {
    id: "exam-prep",
    name: "Exam Preparation",
    description:
      "Organize study topics, practice sessions, and review cycles before exams.",
    bestFor: "Midterms, finals, certification exams",
    category: "General",
    columns: ["Topics to Cover", "Studying", "Practice Tests", "Review", "Ready"],
    initialTasks: [
      { title: "List all exam topics from syllabus", description: "Go through the course syllabus and list every testable topic.", tags: ["Planning"], column: 0 },
      { title: "Gather lecture notes and textbook chapters", description: "Collect all materials for each topic.", tags: ["Research"], column: 0 },
      { title: "Identify weak areas", description: "Mark topics you are less confident about for extra focus.", tags: ["Planning"], column: 0 },
      { title: "Create summary notes per topic", description: "Write concise summaries or flashcards for each topic.", tags: ["Study"], column: 1 },
      { title: "Schedule group study session", description: "Coordinate a study session with classmates.", tags: ["Team"], column: 1 },
      { title: "Watch supplementary videos or tutorials", description: "Find online resources for challenging topics.", tags: ["Study"], column: 1 },
      { title: "Complete one full practice test", description: "Simulate exam conditions and complete a practice test.", tags: ["Practice"], column: 2 },
      { title: "Review incorrect answers", description: "Analyze mistakes and understand the correct solutions.", tags: ["Review"], column: 3 },
      { title: "Final review of key formulas / concepts", description: "Do a last pass over critical concepts the night before.", tags: ["Review"], column: 3 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  EDUCATION TEMPLATES
// ─────────────────────────────────────────────────

export const EDUCATION_TEMPLATES: Template[] = [
  {
    id: "lesson-plan-workflow",
    name: "Lesson Plan Workflow",
    description:
      "Systematic approach to planning high-quality lessons aligned with curriculum outcomes.",
    bestFor: "Daily lesson planning, curriculum units, micro-teaching",
    category: "Education",
    columns: [
      "Curriculum & Outcomes",
      "Learner Analysis",
      "Instructional Strategy",
      "Materials & Activities",
      "Assessment Plan",
      "Final Review",
    ],
    initialTasks: [
      { title: "Identify target curriculum standard", description: "Select the specific curriculum outcome this lesson addresses.", tags: ["Alignment"], column: 0 },
      { title: "Write measurable learning objectives", description: "Draft 2-3 SMART objectives students should achieve.", tags: ["Objectives"], column: 0 },
      { title: "Define prerequisite knowledge", description: "List what students should already know before this lesson.", tags: ["Planning"], column: 0 },
      { title: "Analyze learner characteristics", description: "Consider age, prior knowledge, learning styles, and special needs.", tags: ["Analysis"], column: 1 },
      { title: "Identify potential misconceptions", description: "Anticipate common errors or misunderstandings students may have.", tags: ["Analysis"], column: 1 },
      { title: "Assess available class time", description: "Plan timing for each segment of the lesson.", tags: ["Planning"], column: 1 },
      { title: "Select instructional method", description: "Choose between direct instruction, inquiry-based, cooperative, etc.", tags: ["Strategy"], column: 2 },
      { title: "Plan engagement / warm-up activity", description: "Design an opening activity to activate prior knowledge.", tags: ["Activity"], column: 2 },
      { title: "Design main instructional sequence", description: "Outline the step-by-step teaching flow.", tags: ["Strategy"], column: 2 },
      { title: "Plan differentiation strategies", description: "Prepare adaptations for advanced and struggling learners.", tags: ["Strategy"], column: 2 },
      { title: "Prepare slide deck or board notes", description: "Create visual aids for the lesson presentation.", tags: ["Materials"], column: 3 },
      { title: "Prepare student handouts / worksheets", description: "Design activity sheets or guided notes for students.", tags: ["Materials"], column: 3 },
      { title: "Prepare group activity materials", description: "Set up materials for cooperative learning tasks.", tags: ["Activity"], column: 3 },
      { title: "Design formative assessment questions", description: "Create check-for-understanding questions during the lesson.", tags: ["Assessment"], column: 4 },
      { title: "Create exit ticket or quiz", description: "Design a quick assessment for lesson closure.", tags: ["Assessment"], column: 4 },
      { title: "Define grading rubric or criteria", description: "Establish how student work will be evaluated.", tags: ["Assessment"], column: 4 },
      { title: "Review lesson for coherence", description: "Ensure all parts align: objectives → activities → assessment.", tags: ["Review"], column: 5 },
      { title: "Get peer / mentor feedback", description: "Have a colleague review the lesson plan.", tags: ["Review"], column: 5 },
      { title: "Finalize and save lesson plan", description: "Make final edits and file the completed plan.", tags: ["Final"], column: 5 },
    ],
  },
  {
    id: "instructional-material",
    name: "Instructional Material Development",
    description:
      "Design and create effective classroom learning aids from needs analysis to final evaluation.",
    bestFor: "Teaching materials, visual aids, classroom resources, educational media",
    category: "Education",
    columns: [
      "Needs Analysis",
      "Learning Objectives",
      "Content Design",
      "Visual / Media Production",
      "Classroom Use Plan",
      "Evaluation & Revision",
    ],
    initialTasks: [
      { title: "Identify instructional gap", description: "Determine what learning need the material will address.", tags: ["Analysis"], column: 0 },
      { title: "Survey target audience needs", description: "Gather input from students or teachers about content gaps.", tags: ["Research"], column: 0 },
      { title: "Review existing materials", description: "Evaluate currently available resources and identify shortcomings.", tags: ["Research"], column: 0 },
      { title: "Write clear learning objectives", description: "Define what learners should achieve using this material.", tags: ["Objectives"], column: 1 },
      { title: "Align objectives with curriculum", description: "Ensure material supports official curriculum standards.", tags: ["Alignment"], column: 1 },
      { title: "Define scope and content outline", description: "Outline topics and subtopics the material will cover.", tags: ["Planning"], column: 1 },
      { title: "Draft text content and explanations", description: "Write the instructional text with clear language.", tags: ["Writing"], column: 2 },
      { title: "Design practice exercises", description: "Create activities that reinforce the learning objectives.", tags: ["Design"], column: 2 },
      { title: "Add real-world examples", description: "Include relatable examples and case studies.", tags: ["Content"], column: 2 },
      { title: "Create diagrams and illustrations", description: "Design visual elements that support comprehension.", tags: ["Visual"], column: 3 },
      { title: "Record or source multimedia content", description: "Produce audio, video, or interactive elements if needed.", tags: ["Media"], column: 3 },
      { title: "Format and layout design", description: "Apply professional formatting with consistent visual style.", tags: ["Design"], column: 3 },
      { title: "Write teacher guide / instructions", description: "Create usage instructions for educators.", tags: ["Documentation"], column: 4 },
      { title: "Plan classroom integration strategy", description: "Describe how the material fits into a lesson sequence.", tags: ["Planning"], column: 4 },
      { title: "Prepare student instructions", description: "Write clear directions for student use.", tags: ["Documentation"], column: 4 },
      { title: "Pilot test with sample group", description: "Try the material with a small group and observe results.", tags: ["Testing"], column: 5 },
      { title: "Collect feedback from users", description: "Gather structured feedback from students and teachers.", tags: ["Feedback"], column: 5 },
      { title: "Revise based on evaluation", description: "Improve the material based on pilot test results.", tags: ["Revision"], column: 5 },
    ],
  },
  {
    id: "assessment-report",
    name: "Assessment and Evaluation Report",
    description:
      "Structured workflow for creating comprehensive assessment reports with data analysis.",
    bestFor: "Grade reports, performance analysis, program evaluation",
    category: "Education",
    columns: [
      "Assessment Purpose",
      "Data Collection",
      "Rubric / Criteria Design",
      "Statistical Analysis",
      "Qualitative Feedback",
      "Final Report",
    ],
    initialTasks: [
      { title: "Define assessment purpose and scope", description: "Clarify what the assessment aims to measure and why.", tags: ["Planning"], column: 0 },
      { title: "Identify stakeholders", description: "List who will use the assessment results (teachers, admin, parents).", tags: ["Planning"], column: 0 },
      { title: "Select assessment type", description: "Choose formative, summative, diagnostic, or other type.", tags: ["Design"], column: 0 },
      { title: "Design data collection instruments", description: "Create tests, surveys, observation forms, or rubrics.", tags: ["Design"], column: 1 },
      { title: "Administer assessments to students", description: "Conduct the assessment under standardized conditions.", tags: ["Data"], column: 1 },
      { title: "Input and organize raw data", description: "Enter scores into a spreadsheet with proper labeling.", tags: ["Data Entry"], column: 1 },
      { title: "Develop scoring rubric", description: "Create clear criteria and scoring levels for evaluation.", tags: ["Design"], column: 2 },
      { title: "Calibrate rubric with sample responses", description: "Test the rubric on sample work to ensure consistency.", tags: ["Quality"], column: 2 },
      { title: "Score all student work", description: "Apply the rubric consistently across all submissions.", tags: ["Evaluation"], column: 2 },
      { title: "Calculate descriptive statistics", description: "Compute mean, median, standard deviation, and distributions.", tags: ["Analysis"], column: 3 },
      { title: "Create score distribution charts", description: "Visualize data with histograms, box plots, or bar charts.", tags: ["Visualization"], column: 3 },
      { title: "Identify performance patterns", description: "Look for trends across groups, questions, or topics.", tags: ["Analysis"], column: 3 },
      { title: "Summarize student written feedback", description: "Compile and categorize qualitative responses.", tags: ["Qualitative"], column: 4 },
      { title: "Conduct thematic analysis", description: "Identify recurring themes in open-ended responses.", tags: ["Analysis"], column: 4 },
      { title: "Draft findings section", description: "Write up the key findings from both quantitative and qualitative data.", tags: ["Writing"], column: 5 },
      { title: "Write recommendations", description: "Propose action items based on assessment results.", tags: ["Writing"], column: 5 },
      { title: "Format and finalize report", description: "Apply proper formatting, add appendices, and proofread.", tags: ["Final"], column: 5 },
    ],
  },
  {
    id: "practicum-tracking",
    name: "School Experience and Practicum",
    description:
      "Track your teaching observations, practice sessions, and reflection portfolio.",
    bestFor: "Teaching practicum, field observations, student teaching",
    category: "Education",
    columns: [
      "Observation Planning",
      "Classroom Observation",
      "Teaching Practice",
      "Mentor Feedback",
      "Reflection",
      "Portfolio Submission",
    ],
    initialTasks: [
      { title: "Review practicum requirements", description: "Read the course handbook for observation and teaching hour requirements.", tags: ["Planning"], column: 0 },
      { title: "Schedule observation visits", description: "Coordinate dates with cooperating teacher and school.", tags: ["Planning"], column: 0 },
      { title: "Prepare observation checklist", description: "Create a structured form for recording observations.", tags: ["Preparation"], column: 0 },
      { title: "Observe classroom management techniques", description: "Note how the teacher manages behavior and transitions.", tags: ["Observation"], column: 1 },
      { title: "Observe instructional methods", description: "Document teaching strategies and student engagement.", tags: ["Observation"], column: 1 },
      { title: "Record student interaction patterns", description: "Note participation levels and group dynamics.", tags: ["Observation"], column: 1 },
      { title: "Plan and deliver first lesson", description: "Prepare and teach your first practice lesson.", tags: ["Teaching"], column: 2 },
      { title: "Deliver second lesson with improvements", description: "Apply feedback from first lesson to improve.", tags: ["Teaching"], column: 2 },
      { title: "Manage classroom independently", description: "Lead the class for a full session.", tags: ["Teaching"], column: 2 },
      { title: "Meet with mentor teacher", description: "Discuss your teaching performance and areas for growth.", tags: ["Feedback"], column: 3 },
      { title: "Review mentor evaluation form", description: "Read and understand the formal evaluation feedback.", tags: ["Feedback"], column: 3 },
      { title: "Set improvement goals", description: "Identify 2-3 specific areas to develop.", tags: ["Growth"], column: 3 },
      { title: "Write reflective journal entry", description: "Reflect on your experiences, challenges, and growth.", tags: ["Reflection"], column: 4 },
      { title: "Connect theory to practice", description: "Link your observations to educational theory concepts.", tags: ["Reflection"], column: 4 },
      { title: "Compile portfolio artifacts", description: "Gather lesson plans, evaluations, photos, and reflections.", tags: ["Portfolio"], column: 5 },
      { title: "Write portfolio introduction", description: "Write a cover letter summarizing your practicum experience.", tags: ["Writing"], column: 5 },
      { title: "Submit final portfolio", description: "Upload the completed portfolio to the course system.", tags: ["Submission"], column: 5 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  CEIT TEMPLATES
// ─────────────────────────────────────────────────

export const CEIT_TEMPLATES: Template[] = [
  {
    id: "instructional-design-addie",
    name: "Instructional Design Project (ADDIE)",
    description:
      "Full ADDIE-model workflow for designing instructional interventions from analysis to evaluation.",
    bestFor: "CEIT courses, instructional design projects, ID portfolios",
    category: "CEIT",
    columns: [
      "Analysis",
      "Learning Objectives",
      "Design Strategy",
      "Development",
      "Implementation Plan",
      "Evaluation",
    ],
    initialTasks: [
      { title: "Conduct learner analysis", description: "Profile the target audience: demographics, prior knowledge, learning preferences.", tags: ["Analysis"], column: 0 },
      { title: "Conduct needs analysis", description: "Identify the gap between current and desired performance.", tags: ["Analysis"], column: 0 },
      { title: "Analyze learning context", description: "Evaluate the environment where instruction will take place.", tags: ["Analysis"], column: 0 },
      { title: "Define task / content analysis", description: "Break down the subject matter into teachable components.", tags: ["Analysis"], column: 0 },
      { title: "Write measurable learning objectives", description: "Create objectives using Bloom's taxonomy with action verbs.", tags: ["Objectives"], column: 1 },
      { title: "Align objectives with assessment", description: "Ensure each objective has a corresponding assessment method.", tags: ["Alignment"], column: 1 },
      { title: "Prioritize objectives by importance", description: "Rank objectives to guide content sequencing.", tags: ["Planning"], column: 1 },
      { title: "Select instructional strategies", description: "Choose methods: direct instruction, discovery, problem-based, etc.", tags: ["Design"], column: 2 },
      { title: "Design content sequencing", description: "Organize topics in logical order (simple to complex).", tags: ["Design"], column: 2 },
      { title: "Plan learner interaction and engagement", description: "Design activities that promote active learning.", tags: ["Design"], column: 2 },
      { title: "Create storyboard / content outline", description: "Draft the detailed structure of instructional materials.", tags: ["Design"], column: 2 },
      { title: "Develop instructional materials", description: "Create slides, handouts, or digital content.", tags: ["Development"], column: 3 },
      { title: "Produce multimedia assets", description: "Record videos, create animations, or design infographics.", tags: ["Media"], column: 3 },
      { title: "Build assessment instruments", description: "Create quizzes, rubrics, and performance tasks.", tags: ["Assessment"], column: 3 },
      { title: "Conduct usability review", description: "Have peers test materials for clarity and usability.", tags: ["Quality"], column: 3 },
      { title: "Prepare instructor guide", description: "Write facilitation notes and implementation instructions.", tags: ["Documentation"], column: 4 },
      { title: "Plan pilot implementation", description: "Schedule and prepare for a trial run with sample learners.", tags: ["Planning"], column: 4 },
      { title: "Conduct formative evaluation", description: "Gather data during pilot to identify improvements.", tags: ["Evaluation"], column: 5 },
      { title: "Analyze evaluation data", description: "Review feedback and performance data from the pilot.", tags: ["Analysis"], column: 5 },
      { title: "Write summative evaluation report", description: "Document overall effectiveness and recommendations.", tags: ["Report"], column: 5 },
      { title: "Revise based on findings", description: "Make final improvements to materials and strategy.", tags: ["Revision"], column: 5 },
    ],
  },
  {
    id: "elearning-course",
    name: "E-Learning Course Development",
    description:
      "Build a complete online course from planning through content production to LMS publishing.",
    bestFor: "Online courses, LMS content, Articulate/Storyline projects",
    category: "CEIT",
    columns: [
      "Course Planning",
      "Storyboard",
      "Content Production",
      "Interaction Design",
      "Assessment",
      "Publishing & Testing",
    ],
    initialTasks: [
      { title: "Define course goals and audience", description: "Clarify who the course is for and what they should learn.", tags: ["Planning"], column: 0 },
      { title: "Create module outline", description: "Break the course into modules with topics per module.", tags: ["Planning"], column: 0 },
      { title: "Write learning outcomes per module", description: "Define measurable outcomes for each module.", tags: ["Objectives"], column: 0 },
      { title: "Set up LMS structure", description: "Create the course shell in the LMS (Moodle, Canvas, etc.).", tags: ["Setup"], column: 0 },
      { title: "Create storyboard for Module 1", description: "Design the screen-by-screen flow for the first module.", tags: ["Design"], column: 1 },
      { title: "Map content flow across modules", description: "Ensure logical progression between modules.", tags: ["Design"], column: 1 },
      { title: "Design navigation and UI layout", description: "Plan consistent navigation patterns for learners.", tags: ["UX"], column: 1 },
      { title: "Record / source video content", description: "Create instructional videos or source existing ones.", tags: ["Media"], column: 2 },
      { title: "Create slide-based content", description: "Design presentation slides for each module.", tags: ["Content"], column: 2 },
      { title: "Prepare multimedia assets", description: "Create graphics, animations, and audio narrations.", tags: ["Media"], column: 2 },
      { title: "Write script / narration text", description: "Draft narration scripts for audio or video content.", tags: ["Writing"], column: 2 },
      { title: "Design interactive activities", description: "Create drag-and-drop, hotspot, or branching scenarios.", tags: ["Interaction"], column: 3 },
      { title: "Build discussion prompts", description: "Create forum questions or peer interaction activities.", tags: ["Engagement"], column: 3 },
      { title: "Add gamification elements", description: "Include badges, points, or progress tracking.", tags: ["Engagement"], column: 3 },
      { title: "Create quiz questions per module", description: "Write MCQ, true/false, and open-ended questions.", tags: ["Assessment"], column: 4 },
      { title: "Design final assessment / project", description: "Create a capstone assignment or comprehensive exam.", tags: ["Assessment"], column: 4 },
      { title: "Set grading criteria", description: "Define rubrics and passing scores.", tags: ["Assessment"], column: 4 },
      { title: "Run accessibility check", description: "Verify WCAG compliance for all content.", tags: ["Quality"], column: 5 },
      { title: "Test on multiple devices", description: "Verify content works on desktop, tablet, and mobile.", tags: ["Testing"], column: 5 },
      { title: "Publish and announce course", description: "Make the course live and notify enrolled learners.", tags: ["Launch"], column: 5 },
    ],
  },
  {
    id: "edtech-integration",
    name: "Educational Technology Integration",
    description:
      "Plan, pilot, and evaluate the integration of a digital tool into classroom instruction.",
    bestFor: "EdTech pilot projects, technology integration plans, tool evaluation",
    category: "CEIT",
    columns: [
      "Problem Definition",
      "Tool Selection",
      "Integration Plan",
      "Classroom Activity Design",
      "Testing",
      "Reflection Report",
    ],
    initialTasks: [
      { title: "Identify instructional problem", description: "Define the specific teaching/learning challenge to address.", tags: ["Analysis"], column: 0 },
      { title: "Review current instructional approach", description: "Document how the topic is currently taught.", tags: ["Analysis"], column: 0 },
      { title: "Define success criteria", description: "Establish measurable indicators of improvement.", tags: ["Planning"], column: 0 },
      { title: "Research available digital tools", description: "Survey tools that could address the identified problem.", tags: ["Research"], column: 1 },
      { title: "Compare tools with evaluation matrix", description: "Rate tools on criteria: cost, ease of use, features, support.", tags: ["Evaluation"], column: 1 },
      { title: "Select the best-fit tool", description: "Choose the tool based on evaluation results.", tags: ["Decision"], column: 1 },
      { title: "Design integration plan", description: "Map how the tool will fit into the existing lesson flow.", tags: ["Planning"], column: 2 },
      { title: "Prepare technical requirements", description: "List hardware, software, and connectivity needs.", tags: ["Setup"], column: 2 },
      { title: "Create teacher instructions", description: "Write a guide for educators using the tool.", tags: ["Documentation"], column: 2 },
      { title: "Design classroom activity using the tool", description: "Create a detailed activity plan incorporating the technology.", tags: ["Design"], column: 3 },
      { title: "Prepare student instructions", description: "Write clear step-by-step guides for students.", tags: ["Documentation"], column: 3 },
      { title: "Create supporting materials", description: "Design worksheets or guides that complement the tool.", tags: ["Materials"], column: 3 },
      { title: "Pilot the tool in classroom", description: "Run the activity with a real class and observe.", tags: ["Testing"], column: 4 },
      { title: "Collect student feedback", description: "Survey students about their experience with the tool.", tags: ["Feedback"], column: 4 },
      { title: "Document observations and issues", description: "Note technical issues, engagement levels, and outcomes.", tags: ["Data"], column: 4 },
      { title: "Analyze pilot results", description: "Compare outcomes against success criteria.", tags: ["Analysis"], column: 5 },
      { title: "Write reflection report", description: "Summarize findings, lessons learned, and recommendations.", tags: ["Writing"], column: 5 },
      { title: "Propose improvements for future use", description: "Suggest how to improve the integration for next time.", tags: ["Recommendation"], column: 5 },
    ],
  },
  {
    id: "learning-analytics",
    name: "Learning Analytics / Student Performance",
    description:
      "Analyze student data to identify patterns, visualize performance, and write recommendations.",
    bestFor: "Data-driven projects, student performance studies, educational research",
    category: "CEIT",
    columns: [
      "Data Source Planning",
      "Data Cleaning",
      "Analysis",
      "Visualization",
      "Interpretation",
      "Recommendation Report",
    ],
    initialTasks: [
      { title: "Define metrics and research questions", description: "Decide what performance indicators to track (grades, attendance, engagement).", tags: ["Planning"], column: 0 },
      { title: "Identify data sources", description: "List where data will come from: LMS logs, grade books, surveys.", tags: ["Planning"], column: 0 },
      { title: "Collect raw data", description: "Export scores, participation data, and activity logs.", tags: ["Data"], column: 0 },
      { title: "Handle missing values", description: "Decide how to treat incomplete records.", tags: ["Cleaning"], column: 1 },
      { title: "Standardize data format", description: "Ensure consistent formatting across all data sources.", tags: ["Cleaning"], column: 1 },
      { title: "Remove outliers if appropriate", description: "Identify and handle anomalous data points.", tags: ["Cleaning"], column: 1 },
      { title: "Calculate descriptive statistics", description: "Compute averages, medians, and standard deviations.", tags: ["Statistics"], column: 2 },
      { title: "Perform correlation analysis", description: "Explore relationships between variables.", tags: ["Analysis"], column: 2 },
      { title: "Segment students by performance level", description: "Group students into high/medium/low performers.", tags: ["Analysis"], column: 2 },
      { title: "Create performance distribution charts", description: "Design histograms and box plots of student scores.", tags: ["Charts"], column: 3 },
      { title: "Build trend line graphs", description: "Show how performance changes over time.", tags: ["Charts"], column: 3 },
      { title: "Design comparative visualizations", description: "Create charts comparing groups or time periods.", tags: ["Charts"], column: 3 },
      { title: "Identify key patterns and trends", description: "Summarize the main findings from the analysis.", tags: ["Insights"], column: 4 },
      { title: "Connect findings to literature", description: "Relate patterns to existing educational research.", tags: ["Research"], column: 4 },
      { title: "Discuss limitations", description: "Acknowledge data and methodology constraints.", tags: ["Critical"], column: 4 },
      { title: "Write actionable recommendations", description: "Propose specific interventions based on findings.", tags: ["Recommendations"], column: 5 },
      { title: "Format final report", description: "Compile all sections into a professional report.", tags: ["Writing"], column: 5 },
      { title: "Prepare presentation", description: "Create slides summarizing key findings for stakeholders.", tags: ["Presentation"], column: 5 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  ENGINEERING TEMPLATES
// ─────────────────────────────────────────────────

export const ENGINEERING_TEMPLATES: Template[] = [
  {
    id: "software-sprint",
    name: "Software Development Sprint",
    description:
      "Agile-style sprint board for coding projects with backlog, development, testing, and release.",
    bestFor: "CS projects, hackathons, app development, software engineering courses",
    category: "Engineering",
    columns: ["Backlog", "Planning", "Development", "Testing / QA", "Documentation", "Release"],
    initialTasks: [
      { title: "Define MVP features", description: "List the minimum features needed for a working product.", tags: ["Planning"], column: 0 },
      { title: "Write user stories", description: "Create user stories for each feature: As a [user], I want [feature] so that [benefit].", tags: ["Requirements"], column: 0 },
      { title: "Prioritize features by value", description: "Rank features by importance and feasibility.", tags: ["Planning"], column: 0 },
      { title: "Set up repository and environment", description: "Initialize Git repo, configure dev environment and CI/CD.", tags: ["Setup"], column: 1 },
      { title: "Create sprint backlog", description: "Select stories for the current sprint.", tags: ["Planning"], column: 1 },
      { title: "Assign tasks to developers", description: "Distribute work based on skills and capacity.", tags: ["Team"], column: 1 },
      { title: "Define coding standards", description: "Agree on naming conventions, folder structure, and style guide.", tags: ["Standards"], column: 1 },
      { title: "Implement core feature 1", description: "Build the first priority feature.", tags: ["Coding"], column: 2 },
      { title: "Implement core feature 2", description: "Build the second priority feature.", tags: ["Coding"], column: 2 },
      { title: "Implement API / backend logic", description: "Build server-side endpoints and business logic.", tags: ["Coding"], column: 2 },
      { title: "Build UI components", description: "Create frontend components and views.", tags: ["Frontend"], column: 2 },
      { title: "Write unit tests", description: "Create automated tests for core functions.", tags: ["Testing"], column: 3 },
      { title: "Perform integration testing", description: "Test component interactions end-to-end.", tags: ["Testing"], column: 3 },
      { title: "Fix bugs from testing", description: "Resolve issues found during QA.", tags: ["Bug Fix"], column: 3 },
      { title: "Code review all PRs", description: "Review and approve pull requests.", tags: ["Review"], column: 3 },
      { title: "Write README and setup docs", description: "Document how to install and run the project.", tags: ["Documentation"], column: 4 },
      { title: "Write API documentation", description: "Document endpoints, parameters, and responses.", tags: ["Documentation"], column: 4 },
      { title: "Prepare demo / presentation", description: "Create a demo script or recording.", tags: ["Presentation"], column: 5 },
      { title: "Tag release version", description: "Create a release tag and deploy.", tags: ["Release"], column: 5 },
    ],
  },
  {
    id: "engineering-capstone",
    name: "Engineering Capstone Design",
    description:
      "Complete workflow for capstone engineering projects from problem definition to final presentation.",
    bestFor: "Senior design projects, engineering capstone, interdisciplinary projects",
    category: "Engineering",
    columns: [
      "Problem Definition",
      "Requirements",
      "Concept Design",
      "Prototype",
      "Testing",
      "Final Presentation",
    ],
    initialTasks: [
      { title: "Define the engineering problem", description: "Write a clear problem statement with scope and constraints.", tags: ["Analysis"], column: 0 },
      { title: "Identify stakeholders and end users", description: "List who benefits from the solution.", tags: ["Research"], column: 0 },
      { title: "Conduct background research", description: "Review existing solutions and related literature.", tags: ["Research"], column: 0 },
      { title: "List functional requirements", description: "Define what the system must do.", tags: ["Requirements"], column: 1 },
      { title: "List non-functional requirements", description: "Define performance, safety, and usability constraints.", tags: ["Requirements"], column: 1 },
      { title: "Create requirements traceability matrix", description: "Map requirements to design features and tests.", tags: ["Documentation"], column: 1 },
      { title: "Brainstorm design alternatives", description: "Generate multiple concept solutions.", tags: ["Design"], column: 2 },
      { title: "Evaluate alternatives with decision matrix", description: "Score each concept against weighted criteria.", tags: ["Evaluation"], column: 2 },
      { title: "Create detailed design of selected concept", description: "Develop technical drawings or architecture diagrams.", tags: ["Design"], column: 2 },
      { title: "Build first prototype / MVP", description: "Construct a working model of the design.", tags: ["Build"], column: 3 },
      { title: "Document design decisions", description: "Record why each design choice was made.", tags: ["Documentation"], column: 3 },
      { title: "Iterate on prototype", description: "Improve the prototype based on initial observations.", tags: ["Iteration"], column: 3 },
      { title: "Design test plan", description: "Plan how to verify each requirement.", tags: ["Testing"], column: 4 },
      { title: "Execute tests and record results", description: "Run tests and document outcomes.", tags: ["Testing"], column: 4 },
      { title: "Analyze test results", description: "Evaluate whether requirements are met.", tags: ["Analysis"], column: 4 },
      { title: "Prepare final report", description: "Write the complete capstone design report.", tags: ["Writing"], column: 5 },
      { title: "Create presentation slides", description: "Design a professional presentation for the defense.", tags: ["Presentation"], column: 5 },
      { title: "Practice and deliver presentation", description: "Rehearse and present to the evaluation committee.", tags: ["Presentation"], column: 5 },
    ],
  },
  {
    id: "technical-lab-report",
    name: "Technical Research / Lab Report",
    description:
      "Structured workflow for conducting experiments and writing technical lab reports.",
    bestFor: "Lab courses, experimental research, technical writing",
    category: "Engineering",
    columns: [
      "Research Question",
      "Method",
      "Experiment / Implementation",
      "Data Analysis",
      "Results",
      "Report",
    ],
    initialTasks: [
      { title: "Define research question / hypothesis", description: "State what you aim to investigate or prove.", tags: ["Research"], column: 0 },
      { title: "Review related work", description: "Read relevant papers and past experiments.", tags: ["Literature"], column: 0 },
      { title: "Identify variables", description: "Define independent, dependent, and control variables.", tags: ["Planning"], column: 0 },
      { title: "Design experimental procedure", description: "Write step-by-step methodology.", tags: ["Method"], column: 1 },
      { title: "Prepare equipment list", description: "List all tools, software, and materials needed.", tags: ["Preparation"], column: 1 },
      { title: "Plan data collection approach", description: "Define how data will be measured and recorded.", tags: ["Planning"], column: 1 },
      { title: "Set up experiment environment", description: "Configure hardware, software, or lab setup.", tags: ["Setup"], column: 2 },
      { title: "Conduct experiment / run implementation", description: "Execute the procedure and collect raw data.", tags: ["Execution"], column: 2 },
      { title: "Record observations and notes", description: "Document anything unexpected during the experiment.", tags: ["Data"], column: 2 },
      { title: "Clean and organize data", description: "Format raw data into usable tables.", tags: ["Data"], column: 3 },
      { title: "Perform statistical analysis", description: "Apply appropriate statistical methods.", tags: ["Analysis"], column: 3 },
      { title: "Create charts and graphs", description: "Visualize results with appropriate chart types.", tags: ["Visualization"], column: 3 },
      { title: "Interpret results", description: "Explain what the data shows relative to the hypothesis.", tags: ["Interpretation"], column: 4 },
      { title: "Compare with expected outcomes", description: "Discuss whether results align with predictions.", tags: ["Discussion"], column: 4 },
      { title: "Identify sources of error", description: "Document potential error sources and their impact.", tags: ["Critical"], column: 4 },
      { title: "Write lab report", description: "Compile all sections: intro, method, results, discussion, conclusion.", tags: ["Writing"], column: 5 },
      { title: "Add references and citations", description: "Properly cite all sources used.", tags: ["References"], column: 5 },
      { title: "Proofread and submit", description: "Review for clarity, grammar, and formatting before submission.", tags: ["Final"], column: 5 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  BASIC SCIENCES TEMPLATES
// ─────────────────────────────────────────────────

export const BASIC_SCIENCES_TEMPLATES: Template[] = [
  {
    id: "lab-experiment",
    name: "Laboratory Experiment Report",
    description:
      "Complete scientific method workflow from hypothesis to final lab report.",
    bestFor: "Chemistry, physics, biology lab courses",
    category: "Basic Sciences",
    columns: [
      "Hypothesis",
      "Materials & Method",
      "Experiment",
      "Data Recording",
      "Analysis",
      "Lab Report",
    ],
    initialTasks: [
      { title: "Formulate hypothesis", description: "State a testable prediction based on theory.", tags: ["Theory"], column: 0 },
      { title: "Review theoretical background", description: "Study relevant theory and prior experiments.", tags: ["Literature"], column: 0 },
      { title: "Identify expected outcomes", description: "Predict what results should occur if hypothesis is correct.", tags: ["Planning"], column: 0 },
      { title: "List all required materials", description: "Inventory chemicals, equipment, and safety gear needed.", tags: ["Preparation"], column: 1 },
      { title: "Write detailed procedure", description: "Document step-by-step experimental method.", tags: ["Method"], column: 1 },
      { title: "Review safety protocols", description: "Check MSDS sheets and lab safety requirements.", tags: ["Safety"], column: 1 },
      { title: "Set up apparatus", description: "Assemble and calibrate experimental equipment.", tags: ["Setup"], column: 2 },
      { title: "Conduct experiment", description: "Execute the procedure following the written method.", tags: ["Execution"], column: 2 },
      { title: "Repeat trials for reliability", description: "Run multiple trials to ensure consistent results.", tags: ["Execution"], column: 2 },
      { title: "Record raw measurements", description: "Log all data in lab notebook with units and precision.", tags: ["Data"], column: 3 },
      { title: "Organize data in tables", description: "Create structured data tables for analysis.", tags: ["Organization"], column: 3 },
      { title: "Note any anomalies", description: "Record unexpected observations or deviations.", tags: ["Observation"], column: 3 },
      { title: "Calculate derived quantities", description: "Compute averages, percentages, or derived values.", tags: ["Calculation"], column: 4 },
      { title: "Create graphs and figures", description: "Plot data with proper axes, labels, and trend lines.", tags: ["Visualization"], column: 4 },
      { title: "Calculate percent error", description: "Compare experimental results with theoretical values.", tags: ["Analysis"], column: 4 },
      { title: "Write results and discussion", description: "Interpret findings and relate to hypothesis.", tags: ["Writing"], column: 5 },
      { title: "Write conclusion", description: "Summarize whether hypothesis was supported.", tags: ["Writing"], column: 5 },
      { title: "Submit completed lab report", description: "Format, proofread, and submit the final report.", tags: ["Submission"], column: 5 },
    ],
  },
  {
    id: "research-thesis-science",
    name: "Research & Thesis Preparation",
    description:
      "Structured workflow for scientific research projects from topic selection to final writing.",
    bestFor: "Thesis, research papers, graduation projects, academic research",
    category: "Basic Sciences",
    columns: [
      "Topic Selection",
      "Literature Review",
      "Methodology",
      "Data Collection",
      "Analysis",
      "Final Writing",
    ],
    initialTasks: [
      { title: "Brainstorm research topics", description: "Generate a list of potential research areas.", tags: ["Ideation"], column: 0 },
      { title: "Narrow down to a specific question", description: "Refine the broad topic into a focused research question.", tags: ["Focus"], column: 0 },
      { title: "Discuss with advisor", description: "Get feedback on feasibility and relevance.", tags: ["Mentorship"], column: 0 },
      { title: "Search academic databases", description: "Use Google Scholar, PubMed, or field-specific databases.", tags: ["Research"], column: 1 },
      { title: "Read and annotate key papers", description: "Identify themes, methods, and gaps in existing research.", tags: ["Reading"], column: 1 },
      { title: "Write literature review section", description: "Synthesize findings into a coherent review.", tags: ["Writing"], column: 1 },
      { title: "Define research methodology", description: "Choose qualitative, quantitative, or mixed methods.", tags: ["Design"], column: 2 },
      { title: "Design data collection instruments", description: "Create surveys, interview guides, or experimental protocols.", tags: ["Design"], column: 2 },
      { title: "Obtain ethics approval if needed", description: "Submit to IRB/ethics committee if human subjects involved.", tags: ["Ethics"], column: 2 },
      { title: "Collect data", description: "Execute the data collection according to methodology.", tags: ["Data"], column: 3 },
      { title: "Organize and store data securely", description: "Use structured formats and backup data.", tags: ["Organization"], column: 3 },
      { title: "Maintain research log", description: "Document progress, challenges, and decisions.", tags: ["Documentation"], column: 3 },
      { title: "Analyze data with appropriate methods", description: "Apply statistical tests or qualitative coding.", tags: ["Analysis"], column: 4 },
      { title: "Create tables and figures", description: "Design publication-ready visualizations.", tags: ["Visualization"], column: 4 },
      { title: "Interpret results", description: "Connect findings to research question and literature.", tags: ["Interpretation"], column: 4 },
      { title: "Write discussion and conclusion", description: "Discuss implications, limitations, and future work.", tags: ["Writing"], column: 5 },
      { title: "Format according to guidelines", description: "Apply the required citation style and formatting.", tags: ["Formatting"], column: 5 },
      { title: "Submit final thesis / paper", description: "Complete final review and submit.", tags: ["Submission"], column: 5 },
    ],
  },
  {
    id: "data-analysis-project",
    name: "Data Analysis Project",
    description:
      "End-to-end data analysis workflow from dataset selection through visualization to reporting.",
    bestFor: "Statistics courses, data science, quantitative research",
    category: "Basic Sciences",
    columns: [
      "Dataset Selection",
      "Data Cleaning",
      "Statistical Analysis",
      "Visualization",
      "Interpretation",
      "Report",
    ],
    initialTasks: [
      { title: "Define analysis objectives", description: "Clarify what questions the analysis should answer.", tags: ["Planning"], column: 0 },
      { title: "Find and evaluate datasets", description: "Search for appropriate datasets from reliable sources.", tags: ["Research"], column: 0 },
      { title: "Download and inspect data", description: "Load data and review structure, size, and variables.", tags: ["Exploration"], column: 0 },
      { title: "Handle missing values", description: "Impute, remove, or flag incomplete records.", tags: ["Cleaning"], column: 1 },
      { title: "Detect and handle outliers", description: "Identify extreme values and decide on treatment.", tags: ["Cleaning"], column: 1 },
      { title: "Transform and normalize variables", description: "Scale, encode, or derive new features as needed.", tags: ["Preparation"], column: 1 },
      { title: "Compute descriptive statistics", description: "Calculate mean, median, mode, variance for key variables.", tags: ["Statistics"], column: 2 },
      { title: "Test for statistical significance", description: "Apply t-tests, chi-square, ANOVA, or regression.", tags: ["Testing"], column: 2 },
      { title: "Check assumptions", description: "Verify normality, homogeneity, and independence.", tags: ["Validation"], column: 2 },
      { title: "Create distribution plots", description: "Design histograms, density plots, and box plots.", tags: ["Charts"], column: 3 },
      { title: "Create relationship visualizations", description: "Build scatter plots, correlation matrices, or heatmaps.", tags: ["Charts"], column: 3 },
      { title: "Design summary dashboard", description: "Create an overview visualization combining key findings.", tags: ["Dashboard"], column: 3 },
      { title: "Interpret statistical results", description: "Explain what the numbers mean in context.", tags: ["Insights"], column: 4 },
      { title: "Identify key findings", description: "Highlight the most important patterns and relationships.", tags: ["Summary"], column: 4 },
      { title: "Discuss limitations", description: "Acknowledge data quality issues and scope constraints.", tags: ["Critical"], column: 4 },
      { title: "Write analysis report", description: "Compile methodology, results, and interpretation.", tags: ["Writing"], column: 5 },
      { title: "Include appendices with code", description: "Attach analysis scripts and raw output.", tags: ["Documentation"], column: 5 },
      { title: "Prepare presentation", description: "Create slides summarizing key findings.", tags: ["Presentation"], column: 5 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  BUSINESS / İİBF TEMPLATES
// ─────────────────────────────────────────────────

export const BUSINESS_TEMPLATES: Template[] = [
  {
    id: "business-plan",
    name: "Business Plan Project",
    description:
      "Comprehensive business plan development from idea validation to final investor pitch.",
    bestFor: "Entrepreneurship courses, startup projects, business competitions",
    category: "Business",
    columns: [
      "Business Idea",
      "Market Research",
      "Competitor Analysis",
      "Financial Plan",
      "Risk Analysis",
      "Final Pitch",
    ],
    initialTasks: [
      { title: "Define business idea and value proposition", description: "Articulate what product/service you offer and why it matters.", tags: ["Ideation"], column: 0 },
      { title: "Identify target customer segment", description: "Define who your ideal customers are.", tags: ["Market"], column: 0 },
      { title: "Write executive summary draft", description: "Create a one-page overview of the business.", tags: ["Writing"], column: 0 },
      { title: "Research market size and trends", description: "Estimate TAM, SAM, SOM for your market.", tags: ["Research"], column: 1 },
      { title: "Conduct customer interviews / surveys", description: "Validate assumptions with real potential customers.", tags: ["Primary Research"], column: 1 },
      { title: "Analyze industry reports", description: "Review published data about your target industry.", tags: ["Secondary Research"], column: 1 },
      { title: "Identify main competitors", description: "List direct and indirect competitors in the market.", tags: ["Competition"], column: 2 },
      { title: "Create competitive analysis matrix", description: "Compare features, pricing, and positioning.", tags: ["Analysis"], column: 2 },
      { title: "Define competitive advantage", description: "Articulate your unique differentiator.", tags: ["Strategy"], column: 2 },
      { title: "Create revenue model", description: "Define how the business will make money.", tags: ["Finance"], column: 3 },
      { title: "Build cost structure", description: "Estimate fixed and variable costs.", tags: ["Finance"], column: 3 },
      { title: "Create 3-year financial projections", description: "Project income, expenses, and cash flow.", tags: ["Finance"], column: 3 },
      { title: "Calculate break-even point", description: "Determine when the business becomes profitable.", tags: ["Analysis"], column: 3 },
      { title: "Identify key risks", description: "List market, operational, and financial risks.", tags: ["Risk"], column: 4 },
      { title: "Develop mitigation strategies", description: "Create plans to address each identified risk.", tags: ["Strategy"], column: 4 },
      { title: "Write SWOT analysis", description: "Analyze strengths, weaknesses, opportunities, and threats.", tags: ["Analysis"], column: 4 },
      { title: "Create pitch deck", description: "Design a compelling 10-slide investor presentation.", tags: ["Presentation"], column: 5 },
      { title: "Finalize business plan document", description: "Compile all sections into a professional document.", tags: ["Writing"], column: 5 },
      { title: "Practice and deliver pitch", description: "Rehearse and present to evaluators or investors.", tags: ["Presentation"], column: 5 },
    ],
  },
  {
    id: "marketing-research",
    name: "Marketing Research Project",
    description:
      "Systematic marketing research from problem definition to strategy recommendations.",
    bestFor: "Marketing courses, consumer research, campaign planning",
    category: "Business",
    columns: [
      "Research Problem",
      "Survey / Interview Design",
      "Data Collection",
      "Analysis",
      "Strategy Recommendation",
      "Presentation",
    ],
    initialTasks: [
      { title: "Define marketing research problem", description: "State the business question to be answered.", tags: ["Problem"], column: 0 },
      { title: "Set research objectives", description: "List specific objectives the research should achieve.", tags: ["Objectives"], column: 0 },
      { title: "Review secondary data sources", description: "Check existing reports and published data.", tags: ["Research"], column: 0 },
      { title: "Design survey questionnaire", description: "Create structured questions with proper scales.", tags: ["Design"], column: 1 },
      { title: "Prepare interview guide", description: "Develop open-ended questions for qualitative insights.", tags: ["Design"], column: 1 },
      { title: "Pilot test the instrument", description: "Test with a small group and refine questions.", tags: ["Testing"], column: 1 },
      { title: "Define sampling strategy", description: "Choose sample size and selection method.", tags: ["Methodology"], column: 1 },
      { title: "Distribute surveys", description: "Send out surveys via online or in-person channels.", tags: ["Collection"], column: 2 },
      { title: "Conduct interviews", description: "Run face-to-face or online interviews.", tags: ["Collection"], column: 2 },
      { title: "Monitor response rates", description: "Track completion rates and send reminders.", tags: ["Tracking"], column: 2 },
      { title: "Clean and code data", description: "Prepare collected data for analysis.", tags: ["Data"], column: 3 },
      { title: "Run statistical analysis", description: "Apply appropriate tests: chi-square, regression, factor analysis.", tags: ["Analysis"], column: 3 },
      { title: "Identify consumer insights", description: "Extract key findings about customer behavior and preferences.", tags: ["Insights"], column: 3 },
      { title: "Develop marketing strategy recommendations", description: "Translate findings into actionable marketing strategies.", tags: ["Strategy"], column: 4 },
      { title: "Propose marketing mix adjustments", description: "Suggest changes to product, price, place, or promotion.", tags: ["4P"], column: 4 },
      { title: "Estimate budget requirements", description: "Project costs for recommended strategies.", tags: ["Budget"], column: 4 },
      { title: "Create research report", description: "Write the complete report with methodology and findings.", tags: ["Writing"], column: 5 },
      { title: "Design presentation slides", description: "Create a visual summary for stakeholders.", tags: ["Design"], column: 5 },
      { title: "Present findings and recommendations", description: "Deliver the presentation to the class or client.", tags: ["Delivery"], column: 5 },
    ],
  },
  {
    id: "case-analysis",
    name: "Case Analysis Report",
    description:
      "Structured case study analysis from reading through theoretical framework to recommendation.",
    bestFor: "Management courses, strategy classes, MBA case competitions",
    category: "Business",
    columns: [
      "Case Reading",
      "Problem Identification",
      "Theoretical Framework",
      "Alternative Solutions",
      "Recommendation",
      "Final Report",
    ],
    initialTasks: [
      { title: "Read case study thoroughly", description: "Read the full case at least twice, highlighting key facts.", tags: ["Reading"], column: 0 },
      { title: "Summarize key facts and timeline", description: "Create a timeline of events and key data points.", tags: ["Summary"], column: 0 },
      { title: "Identify stakeholders", description: "List all parties affected by the situation.", tags: ["Analysis"], column: 0 },
      { title: "Define the central problem", description: "State the main issue or decision facing the organization.", tags: ["Problem"], column: 1 },
      { title: "Identify sub-problems", description: "Break down the main problem into component issues.", tags: ["Analysis"], column: 1 },
      { title: "Distinguish symptoms from root causes", description: "Differentiate between surface issues and underlying causes.", tags: ["Critical Thinking"], column: 1 },
      { title: "Select relevant theories / models", description: "Choose frameworks: Porter's Five Forces, SWOT, BCG Matrix, etc.", tags: ["Theory"], column: 2 },
      { title: "Apply framework to case facts", description: "Map case data to the chosen analytical framework.", tags: ["Application"], column: 2 },
      { title: "Draw insights from analysis", description: "Identify patterns and strategic implications.", tags: ["Insights"], column: 2 },
      { title: "Generate alternative solutions", description: "Propose 3-4 distinct courses of action.", tags: ["Brainstorm"], column: 3 },
      { title: "Evaluate pros and cons of each", description: "Analyze feasibility, cost, risk, and impact.", tags: ["Evaluation"], column: 3 },
      { title: "Compare alternatives with criteria", description: "Use a decision matrix to rank options.", tags: ["Decision"], column: 3 },
      { title: "Select best recommendation", description: "Choose and justify the preferred solution.", tags: ["Decision"], column: 4 },
      { title: "Develop implementation plan", description: "Outline steps, timeline, and responsibilities.", tags: ["Planning"], column: 4 },
      { title: "Address potential objections", description: "Anticipate and counter arguments against your recommendation.", tags: ["Critical"], column: 4 },
      { title: "Write case analysis report", description: "Compile all sections into a structured report.", tags: ["Writing"], column: 5 },
      { title: "Add exhibits and appendices", description: "Include supporting data, charts, and calculations.", tags: ["Documentation"], column: 5 },
      { title: "Proofread and submit", description: "Review for clarity, grammar, and proper formatting.", tags: ["Final"], column: 5 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  TEAM TEMPLATES (kept but refined)
// ─────────────────────────────────────────────────

export const TEAM_TEMPLATES: Template[] = [
  {
    id: "event-planning",
    name: "Event Planning",
    description:
      "Coordinate tasks for organizing events, workshops, or campus activities.",
    bestFor: "Student clubs, workshops, conferences, presentations",
    category: "Team",
    columns: ["Ideation", "Planning", "Preparation", "Execution", "Wrap-up"],
    initialTasks: [
      { title: "Define event goals and audience", description: "Clarify the purpose and target attendees.", tags: ["Planning"], column: 0 },
      { title: "Brainstorm event format and theme", description: "Decide on the style and concept of the event.", tags: ["Ideation"], column: 0 },
      { title: "Set date and reserve venue", description: "Book the location and set the event date.", tags: ["Logistics"], column: 1 },
      { title: "Create task checklist", description: "List all tasks and assign deadlines.", tags: ["Organization"], column: 1 },
      { title: "Assign team responsibilities", description: "Distribute roles: MC, logistics, marketing, etc.", tags: ["Team"], column: 1 },
      { title: "Design promotional materials", description: "Create posters, social media posts, and invitations.", tags: ["Marketing"], column: 2 },
      { title: "Prepare equipment and supplies", description: "Arrange AV equipment, name tags, refreshments, etc.", tags: ["Logistics"], column: 2 },
      { title: "Conduct rehearsal or walkthrough", description: "Practice the event flow and check all equipment.", tags: ["Preparation"], column: 2 },
      { title: "Execute event day tasks", description: "Run the event according to plan.", tags: ["Execution"], column: 3 },
      { title: "Document with photos and notes", description: "Capture the event for records and social media.", tags: ["Documentation"], column: 3 },
      { title: "Collect attendee feedback", description: "Distribute surveys or feedback forms.", tags: ["Feedback"], column: 4 },
      { title: "Write event summary report", description: "Document outcomes, attendance, and lessons learned.", tags: ["Report"], column: 4 },
    ],
  },
];

// ─────────────────────────────────────────────────
//  AGGREGATION
// ─────────────────────────────────────────────────

export const ALL_TEMPLATES: Template[] = [
  ...GENERAL_TEMPLATES,
  ...EDUCATION_TEMPLATES,
  ...CEIT_TEMPLATES,
  ...ENGINEERING_TEMPLATES,
  ...BASIC_SCIENCES_TEMPLATES,
  ...BUSINESS_TEMPLATES,
  ...TEAM_TEMPLATES,
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "General",
  "Education",
  "CEIT",
  "Engineering",
  "Basic Sciences",
  "Business",
  "Team",
] as const;

export function getTemplateById(templateId: string) {
  return ALL_TEMPLATES.find((template) => template.id === templateId);
}
